name: Datasets

on:
  push:
      branches:
          - main
      tags:
          - '*'
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                python-version: '3.10'
            - name: Install poetry
              uses: abatilo/actions-poetry@v3
            - name: Install heinlein and datasets
              run: poetry install --with develop
    
    publish:
        runs-on: ubuntu-latest
        needs: build
        if: startsWith(github.ref, 'refs/tags/')
        strategy:
            matrix:
                dataset: ["cfht", "des", "hsc", "ms"]
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                python-version: '3.10'
            - name: Install poetry
              uses: abatilo/actions-poetry@v3
            - name: Publish
              run: |
                cd datasets/${{ matrix.dataset }}
                poetry build
                poetry publish
              env:
                  POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_API_TOKEN }}
                
        
