name: Datasets

on:
    push:
        branches:
            - main
        paths:
            - 'datasets/**'
    pull_request:
    workflow_dispatch:
jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                dataset": ["des", "hsc", "cfht", "ms"]
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                python-version: '3.10'
            - name: Install poetry
              uses: abatilo/actions-poetry@v3
            - name: Install heinlein and datasets
              run: poetry install --with develop
                
        
